# 访问数据库必须的配置
# 47.103.217.162是我远程服务器的公网IP
# 3306是在阿里云中为 MYSQL 开设的端口号

spring:
  redis:
    host: 47.103.217.162
    port: 6379
    database: 0
    password: yl1999122
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
  cache:
    redis:
      time-to-live: -1 #毫秒

  datasource:
    username: root
    password: yl1999122
    url: jdbc:mysql://47.103.217.162:3306/graduation?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

    #使用自定义的数据源(这里是Druid)
    type: com.alibaba.druid.pool.DruidDataSource

    # 在下面指定需要执行的文件路径(数组形式：注意,' classpath: '后面没有空格)
    #    schema:
    #      - classpath:sql/department.sql
    #      - classpath:sql/employee.sql

    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,slf4j  # log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # JPA相关的基本配置
  jpa:
    hibernate:
      ddl-auto: update # 更新或者创建数据表结构
    show-sql: true # 控制台显示SQL


# 日志相关的配置
#logging:
#  level:
#    root: info
#    com.imcoding: debug
#  file:
#    path: log/imcoding.log

# SpringBoot 2.x版本需要加上 下面这行配置
spring.datasource.initialization-mode: always
